name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    env:
      TF_INPUT: false
      TF_IN_AUTOMATION: true

    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Terraform Setup"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3

      - name: "Terraform Format"
        run: terraform fmt -check
        continue-on-error: true
        working-directory: ./terraform

      - name: "Terraform Format"
        run: terraform init
        working-directory: ./terraform

      - name: "Terraform Validate"
        run: terraform validate
        working-directory: ./terraform

      - name: "Terraform Plan"
        run: terraform plan
        working-directory: ./terraform
        env:
          TF_VAR_ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          TF_VAR_ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
