name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VERSION: 1.10.3
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Terraform Setup"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: "Terraform Format"
        run: terraform fmt
        working-directory: ./terraform

      - name: "Terraform Format"
        run: terraform init
        working-directory: ./terraform

      - name: "Terraform Validate"
        run: terraform validate
        working-directory: ./terraform

      - name: "Terraform Plan"
        run: terraform plan
        working-directory: ./terraform
