name: Terraform Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/terraform-*.yaml
      - terraform/*.tf*

jobs:
  terraform:
    name: Terraform
    env:
      TF_INPUT: false
      TF_IN_AUTOMATION: true

    runs-on: ubuntu-24.04

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.TERRAFORM_STATE_ROLE }}
          aws-region: eu-west-1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3
          terraform_wrapper: true

      - name: Terraform Init
        run: terraform init -lockfile=readonly

      - name: Terraform Plan
        run: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_RO_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
