name: Terraform Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/terraform-*.yaml
      - terraform/*.tf*

jobs:
  terraform:
    name: Terraform
    env:
      TF_INPUT: false
      TF_IN_AUTOMATION: true

    runs-on: ubuntu-24.04

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 #v5.0.0
        with:
          role-to-assume: ${{ vars.TERRAFORM_STATE_ROLE }}
          aws-region: eu-west-1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd #v3.1.2
        with:
          terraform_version: 1.13.3
          terraform_wrapper: true

      - name: Terraform Init
        run: terraform init -lockfile=readonly

      - name: Terraform Plan
        run: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_RO_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
